####-DATA DIRI-####
GET http://localhost:5000/data_diri
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
GET http://localhost:5000/data_diri_full
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
POST http://localhost:5000/data_diri
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "nama": "Delvito Rahim Derivansyah",
    "tempat_lahir": "Bandung",
    "tanggal_lahir": "2003-10-09T09:30:00Z",
    "alamat": "Sukasari",
    "email": "vitorahim@gmail.com",
    "no_telp": "03984989348",
    "foto": "ada aja",
    "deskripsi": "asdd",
    "linkedin": "asdd",
    "instagram": "asdd",
    "x": "asdd",
    "github": "asdd"
}

###
PATCH http://localhost:5000/data_diri
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "nama": "Delvito Rahim Derivansyah",
    "tempat_lahir": "Bandung",
    "tanggal_lahir": "2003-10-09T09:30:00Z",
    "alamat": "Sukasari IV",
    "email": "vitorahim@gmail.com",
    "no_telp": "081919191919",
    "foto": "ada ada aja",
    "deskripsi": "weis weis",
    "linkedin": "asdd",
    "instagram": "asdd",
    "x": "asdd",
    "github": "asdd"
}


###
DELETE http://localhost:5000/data_diri
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g




######################################################################


###
GET  http://localhost:5000/admin
###
=======
####-ACCOUNT-####
POST http://localhost:5000/admin
Content-Type: application/json

{
    "username":"admin",
    "email": "admin@gmail.com",
    "password": "123",
    "confPassword": "123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123"
}

###
GET http://localhost:5000/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NTM5NTIzOCwiZXhwIjoxNjk1Mzk1MjU4fQ.EZLXHpTdbN93Wxup-H2wnXq93aUtxx-QI1r2on3ufkk

###
GET http://localhost:5000/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU2NDM2MiwiZXhwIjoxNjk2NTY0MzgyfQ.4SlW4WO3_s3tMBc2gZOW49bnNEaWSexK9Sgw1kBPOqU
###
DELETE  http://localhost:5000/logout



######################################################################


####-GALERI-####
GET http://localhost:5000/datadiri/galeri
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
GET http://localhost:5000/datadiri/galeri/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
POST http://localhost:5000/datadiri/galeri
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "nama_kegiatan": "Kegiatan Gian yang kedua",
    "image": ["img-1.jpg", "img-2.jpg", "img-3.jpg"],
    "deskripsi": "Kegiatan ini dilakukan di Pangelengan" 
}

###
PATCH http://localhost:5000/datadiri/galeri/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "nama_kegiatan": "Kegiatan DRD dua",
    "image": ["img-1.jpg", "img-2.jpg", "img-3.jpg", "img-4.jpg"],
    "deskripsi": "Kegiatan ini dilakukan di Ciwidey" 
}

###
DELETE http://localhost:5000/datadiri/galeri/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g




######################################################################



####-ORGANISASI-####
GET http://localhost:5000/datadiri/organisasi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
GET http://localhost:5000/datadiri/organisasi/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
POST http://localhost:5000/datadiri/organisasi
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "nama_organisasi": "HIMAJAS",
    "jabatan": "Wakadep Rohis",
    "awal_periode": "2003-01-01T00:00:00Z",
    "akhir_periode": "2023-12-31T23:59:59Z",
    "deskripsi": "" 
}

###
PATCH http://localhost:5000/datadiri/organisasi/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "nama_organisasi": "HIMAJAS",
    "jabatan": "Wakadep Mie Ayam",
    "awal_periode": "2003-01-01T00:00:00Z",
    "akhir_periode": "2023-12-31T23:59:59Z",
    "deskripsi": ""   
}

###
DELETE http://localhost:5000/datadiri/organisasi/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g



######################################################################


####-PENDIDIKAN-####
GET http://localhost:5000/datadiri/pendidikan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
GET http://localhost:5000/datadiri/pendidikan/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
POST http://localhost:5000/datadiri/pendidikan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "nama_instansi": "SMPN 1 Bandung",
    "awal_periode": "2018-09-22T14:30:00Z",
    "akhir_periode": "2021-09-22T14:30:00Z",
    "jurusan": ""
}

###
PATCH http://localhost:5000/datadiri/pendidikan/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "nama_instansi": "SMAN 1 Payakumbuh",
    "awal_periode": "2018-09-22T14:30:00Z",
    "akhir_periode": "2021-09-22T14:30:00Z",
    "jurusan": "IPS"
}

###
DELETE http://localhost:5000/datadiri/pendidikan/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g


######################################################################


####-PORTOFOLIO-####
GET http://localhost:5000/datadiri/portofolio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
GET http://localhost:5000/datadiri/portofolio/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
POST http://localhost:5000/datadiri/portofolio
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "judul": "PORTOFOLIYO",
    "deskripsi": "Deskripsi Portofoliooo",
    "file": "Nama Fileeee",
    "image": ["Image1.jpg", "Image2.jpg", "Image2.jpg", "Image3.jpg", "Image4.jpg"],
    "link": "https://www.contohlink.com" 
}

###
PATCH http://localhost:5000/datadiri/portofolio/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "judul": "PORTOFOLIYO",
    "deskripsi": "Deskripsi PRTFL",
    "file": "Nama FILE",
    "image": ["Image3.jpg", "Image4.jpg"],
    "link": "https://www.contohling.com" 
}

###
DELETE http://localhost:5000/datadiri/portofolio/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g


######################################################################


####-SKILL-####
GET http://localhost:5000/datadiri/skill
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
GET http://localhost:5000/datadiri/skill/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

###
POST http://localhost:5000/datadiri/skill
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "nama_skill": "MS Teams",
    "level_keahlian": 5
}

###
PATCH http://localhost:5000/datadiri/skill/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g

{
    "nama_skill": "MS Excel",
    "level_keahlian": 4
}

###
DELETE http://localhost:5000/datadiri/skill/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NjU3NTA4NCwiZXhwIjoxNjk2NTc4Njg0fQ.oYQGEjqi9X_Oh2Io_BdFRp5xbpXgy9aKv0hyq3FfG8g